# SPDX-License-Identifier: Apache-2.0
#
# Copyright (C) 2026 JiaY-shi

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for the generic PWM fan controller
LUCI_DEPENDS:=+luci-base +fancontrol

PKG_LICENSE:=Apache-2.0
PKG_MAINTAINER:=JiaY-shi <shi05275@163.com>

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
