#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@turboacc[-1]
	add ucitrack turboacc
	set ucitrack.@turboacc[-1].init=turboacc
	commit ucitrack
EOF

local hw_flow=0
[ -n "$(cat /etc/openwrt_release | grep 'mt762')" ] && hw_flow=1
uci -q batch <<-EOF >/dev/null
	set turboacc.config.hw_flow=${hw_flow}
	commit turboacc
EOF

exit 0
