#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@turboacc[-1]
	add ucitrack turboacc
	set ucitrack.@turboacc[-1].init=turboacc
	commit ucitrack
EOF

grep -q "mt762" "/etc/openwrt_release" || { uci -q set turboacc.config.hw_flow=0; uci -q commit turboacc; }

exit 0
