#
# Copyright (C) 2008-2019 Jerrykuku
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=Argon Theme
LUCI_DEPENDS:=+luci-base
PKG_VERSION:=2.3.2
PKG_RELEASE:=20240403

CONFIG_LUCI_CSSTIDY:=

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
