# Copyright (C) 2016 Openwrt.org
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for PPPoE Relay
LUCI_DEPENDS:=+luci-compat +rp-pppoe-common +rp-pppoe-relay

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature


