#!/bin/sh

if [ "$(uci -q get unblockneteasemusic.config.music_source)" = "default" ]; then
	uci -q delete unblockneteasemusic.config.music_source
	uci -q commit unblockneteasemusic
fi

uci -q batch <<-EOF >"/dev/null"
	delete ucitrack.@unblockneteasemusic[-1]
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
exit 0
