#!/bin/sh /etc/rc.common
USE_PROCD=1
START=99

start_service() {
    procd_open_instance
    procd_set_param command /usr/share/serverchan/serverchan
    procd_set_param respawn
    procd_close_instance
    echo "serverchan is starting now ..."
}

stop_service() {
    kill -9 `pgrep -f "/usr/share/serverchan/serverchan"` 2>/dev/null
    echo "serverchan exit ..."
}

restart() {
    stop
    start
}

status() {
    state=$(pgrep -f "/usr/share/serverchan/serverchan")
    if [ -z "$state" ]; then
        echo "serverchan is not running."
        return 1
    else
        echo "serverchan is running."
        instances='{"serverchan": {"instances": {"serverchan": {"running": true}}}}'
        echo $instances
        return 0
    fi
}
