include $(TOPDIR)/rules.mk

LUCI_TITLE:=NJIT 802.1X Client for LuCI
LUCI_DESCRIPTION:=This package contains LuCI configuration pages for njit8021xclient.
LUCI_DEPENDS:=+luci-compat +njit8021xclient

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
