#!/bin/sh

[ $(uci -q get "argon.@global[0].bg_mode") ] && exit 0

bing_background="$(uci -q get "argon.@global[0].bing_background")"
if [ "$bing_background" = "1" ]; then
	uci -q set "argon.@global[0].online_wallpaper"="bing"
	uci -q del "argon.@global[0].bing_background"
elif [ "$bing_background" = "0" ]; then
	uci -q del "argon.@global[0].bing_background"
fi

online_wallpaper="$(uci -q get "argon.@global[0].online_wallpaper")"
if [ ! "$online_wallpaper" ]; then
	uci -q set "argon.@global[0].bg_mode"="local_media"
elif [ "$online_wallpaper" = "none" ]; then
	uci -q set "argon.@global[0].bg_mode"="local_media"
	uci -q del "argon.@global[0].online_wallpaper"
else
	uci -q set "argon.@global[0].bg_mode"="online_wallpaper"
fi
uci -q commit "argon"

exit 0
