#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=Open App Filter Module
LUCI_PKGARCH:=all
LUCI_DEPENDS:=+appfilter +luci-compat

PKG_VERSION:=5.0.2

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
