# Copyright (C) 2016 Openwrt.org
# Copyright (C) 2024 iv7777 <hongba@rocketmail.com>
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for Timewol
LUCI_PKGARCH:=all
PKG_VERSION:=1.1
PKG_RELEASE:=1-20240520

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature


