#!/bin/sh /etc/rc.common
# Created By immortalwrt
# https://github.com/immortalwrt

START=99
USE_PROCD=1

CONF="ssocks"
PROG="/usr/bin/ssocksd"

get_config() {
	config_get_bool enable "$1" 'enable' '0'
	config_get bind_addr "$1" 'bind_addr'
	config_get listen_port "$1" 'listen_port'
	config_get username "$1" 'username'
	config_get password "$1" 'password'

    config_load network
	config_get lan_addr "lan" 'ipaddr'
}

start_service() {
	stop_service
	config_load "$CONF"
	config_foreach get_config "$CONF"

	[ "$enable" = "1" ] || return 1

	mkdir -p "/tmp/"
	mkdir -p "/var/etc/"

	[ "${bind_addr}" == "lan" ] && bind_address="${lan_addr}" || bind_address="0.0.0.0"

	if [ -n "${username}" ] && [ -n "${password}" ]; then
		rm -f /etc/config/ssocks-authorization
		echo "${username}:${password}" > /etc/config/ssocks-authorization
		auth_arg="--auth /etc/config/ssocks-authorization"
	fi

	procd_open_instance "$CONF"
	procd_set_param command "$PROG"
	procd_append_param command --port "${listen_port}" --bind "${bind_address}" ${auth_arg} >/dev/null 2>&1 &
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_set_param respawn
	procd_close_instance

	iptables -I INPUT -p tcp --dport "${listen_port}" -j ACCEPT
	cat <<-EOF > "/var/etc/ssocks.include"
iptables -I INPUT -p tcp --dport "${listen_port}" -j ACCEPT
	EOF
}

service_triggers() {
	procd_add_reload_trigger "$CONF"
}

reload_service() {
	stop
	start
}

stop_service() {
	killall -3 ssocksd >/dev/null 2>&1
	rm -f "/etc/config/ssocksd-authorization"
	rm -f "/var/etc/ssocks.include"
}
