#
# Copyright (C) 2015-2016 Openwrt.org
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for ngrokc.
LUCI_DESCRIPTION:=LuCI Support for ngrokc.
LUCI_DEPENDS:=+luci-compat +ngrokc

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
