name: Test Formalities

on:
  pull_request:

jobs:
  build:
    name: Test Formalities
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Determine branch name
        run: |
          BRANCH="${GITHUB_BASE_REF#refs/heads/}"
          echo "Building for $BRANCH"
          echo "BRANCH=$BRANCH" >> $GITHUB_ENV

      - name: Test for merge commits, subject, S.O.B., and email
        run: |
          source .github/workflows/ci_helpers.sh

          RET=0
          for commit in $(git rev-list HEAD ^origin/$BRANCH); do
            info "=== Checking commit '$commit'"
            if git show --format='%P' -s $commit | grep -qF ' '; then
              err "Pull request should not include merge commits"
              RET=1
            fi

            subject="$(git show -s --format=%s $commit)"
            if echo "$subject" | grep -q -e '^[0-9A-Za-z,+/_-]\+: ' -e '^Revert '; then
              success "Commit subject line seems ok ($subject)"
            elif echo "$subject" | grep -iq '^Translated using Weblate.*'; then
              success "Weblate commit subject line exception OK: $subject"
            elif echo "$subject" | grep -iq '^Added translation using Weblate.*'; then
              success "Weblate commit subject line exception OK: $subject"
            else
              err "Commit subject line MUST start with '<package name>: ' ($subject)"
              RET=1
            fi
          done

          exit $RET
