# SPDX-License-Identifier: Apache-2.0
#
# Copyright (C) 2026 ImmortalWrt.org

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for rtp2httpd
LUCI_DEPENDS:=+rtp2httpd

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
